# Generated by Django 6.0.3 on 2026-04-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_options_alter_person_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Endereço'),
        ),
    ]
